name: CI

on:
  push:
    paths-ignore: ['**/*.md']
  pull_request:
    paths-ignore: ['**/*.md']
  workflow_dispatch:

jobs:
  linux:
    uses: ./.github/workflows/linux.yml
    permissions:
      contents: write

  macOS:
    uses: ./.github/workflows/macos.yml
    permissions:
      contents: write

  windows:
    uses: ./.github/workflows/windows.yml
    permissions:
      contents: write
