name: Lint

on:
  workflow_call:

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Cache
        uses: actions/cache/restore@v3
        with:
          path: |
            vlang
            ~/.vmodules
          key: ${{ runner.os }}-
          fail-on-cache-miss: true

      - name: Setup V
        uses: vlang/setup-v@v1.3

      - name: Checkout ${{ env.REPO_NAME }}
        uses: actions/checkout@v3
        with:
          path: ${{ env.REPO_NAME }}

      - name: Check Formatting
        run: v fmt -verify ${{ env.REPO_NAME }}
