name: macOS

on:
  workflow_call:

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  setup:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ${{ env.REPO_NAME }}
    steps:
      - name: Checkout ${{ env.REPO_NAME }}
        uses: actions/checkout@v4
        with:
          path: ${{ env.REPO_NAME }}
      - name: Checkout V
        uses: actions/checkout@v4
        with:
          repository: 'vlang/v'
          path: vlang
      - name: Setup V
        run: cd ../vlang && make -j4 && ./v symlink && v version
      - name: Setup modules
        run: |
          v install
          ~/.vmodules/webview/build.vsh
      - name: Cache
        uses: actions/cache/save@v3
        with:
          path: |
            vlang
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}

  build:
    needs: setup
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ${{ env.REPO_NAME }}
    steps:
      - name: Checkout ${{ env.REPO_NAME }}
        uses: actions/checkout@v4
        with:
          path: ${{ env.REPO_NAME }}
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            vlang
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Setup V
        run: ../vlang/v symlink && v version
      - name: Build
        run: v -cg .

  deploy:
    needs: build
    runs-on: macos-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ${{ env.REPO_NAME }}
    env:
      ARTIFACT: emoji-mart-macos-amd64
    steps:
      - name: Checkout ${{ env.REPO_NAME }}
        uses: actions/checkout@v4
        with:
          path: ${{ env.REPO_NAME }}
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            vlang
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Setup V
        run: ../vlang/v symlink && v version
      - name: Prepare deployment build
        run: |
          curl -sSLo lvb https://github.com/ttytm/LVbag/releases/latest/download/lvb-macos-amd64
          sudo chmod +x ./lvb
          ./lvb --version
          git fetch --prune --unshallow
      - name: Build
        run: ./build.vsh
      - name: Prepare artifacts
        run: mv "dist/emoji-mart" ./$ARTIFACT
      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.REPO_NAME }}/${{ env.ARTIFACT }}
      - name: Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.REPO_NAME }}/${{ env.ARTIFACT }}
