name: macOS

on:
  workflow_call:

env:
  REPO_NAME: ${{ github.event.repository.name }}
  # Path where the module is installed with `v install <giturl>`
  MOD_PATH: ~/.vmodules/webview

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true
      - name: Setup webview
        run: |
          v install --git https://github.com/ttytm/webview
          ~/.vmodules/webview/build.vsh
      - name: Cache
        uses: actions/cache/save@v3
        with:
          path: |
            vlang
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}

  build:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Restore Cache
        uses: actions/cache/restore@v3
        with:
          path: |
            vlang
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Setup V
        uses: vlang/setup-v@v1.3
      - name: Checkout ${{ env.REPO_NAME }}
        uses: actions/checkout@v3
      - name: Build
        run: v -cg .
